### ISSUE TITLE
Possibility to remove monitored Domains

### ISSUE THREAD

**Issue by DocBrown101** [memphisx/netcheck-api#130]

**Comment by memphisx** [comment]
For the record, the backend supports deleting a monitored domain, but I haven't yet exposed the functionality to the frontend. Once I get some free time I will release an update to the frontend as part of https://github.com/memphisx/netcheck-frontend/issues/40 

You can check out the endpoint and test it by going to the API docs endpoint (that would be https://demo.ncheck.eu/docs/v1/swagger-ui/index.html?configUrl=/docs/v1/OpenAPIv3/swagger-config#/Scheduled%20Domain%20Checks/deleteScheduledDomain in the demo) - the link to the OpenAPI docs for your instance is in the info page of the app

For your convenience @DocBrown101 I will keep that issue open until https://github.com/memphisx/netcheck-frontend/issues/40 is closed/released

**Comment by memphisx** [comment]
@DocBrown101 With v0.8.0 of the frontend you can now remove domains from the monitored list. I also hope you like the changes in the UI. I consider this issue closed now but feel free to open another issue if there is anything else.
